// Auto-generated by scripts/export_lr_coefs.py - DO NOT EDIT
// 7-parameter logistic regression for AF detection (RRI features)
// score = coef[0..5] * feat[0..5] + bias ; p_af = sigmoid(score)
// p_af >= k_af_lr_threshold -> anomaly (AF)
//
// Features:
//   feat[0] rri_std   RR interval std (ms)
//   feat[1] rmssd     sqrt(mean(diff(RRI)^2)) (ms)
//   feat[2] pnn50     fraction |diff(RRI)| > 50ms
//   feat[3] cv        RRI std / RRI mean
//   feat[4] hr_proxy  beats/sec proxy
//   feat[5] diff_std  std of first difference of waveform
//
// Source: model/af/af_model_lr.npz (val AUC 0.928, patient-isolated)

#pragma once

#include <stdint.h>

#define K_AF_LR_N_FEATURES 6
#define K_AF_LR_N_PARAMS   7

static const float k_af_lr_coef[K_AF_LR_N_FEATURES] = {
    -0.006531655f, -0.002547544f, 4.2763f,
    6.720686f, 1.255677f, 0.1754746f,
};

static const float k_af_lr_bias = -3.732672f;

static const float k_af_lr_threshold = 0.5f;

static inline float af_lr_score(const float feat[K_AF_LR_N_FEATURES])
{
    float s = k_af_lr_bias;
    for (int i = 0; i < K_AF_LR_N_FEATURES; i++) {
        s += k_af_lr_coef[i] * feat[i];
    }
    return s;
}

static inline float af_lr_sigmoid(float z)
{
    return 1.0f / (1.0f + __builtin_expf(-z));
}
