#!/usr/bin/env python3
"""将训练好的 7 参数逻辑回归导出为固件 C 头文件（方案 A）。

7 参数 LR 的部署形态是硬编码系数（6 权重 + 1 偏置），固件做一次 6 维内积
+sigmoid 即可，零运行时依赖、零解析开销。头文件同时携带特征名注释与
版本信息，保证训练端与固件端的一致性。

用法：
    python scripts/export_lr_coefs.py \
        --weights model/af/af_model_lr.npz \
        --output firmware/main/af_lr_coefs.h

输出：firmware/main/af_lr_coefs.h
    K_AF_LR_N_FEATURES=6, k_af_lr_coef[6], k_af_lr_bias, k_af_lr_threshold
"""

import argparse
import os
from string import Template

import numpy as np

DEFAULT_WEIGHTS = os.path.join("model", "af", "af_model_lr.npz")
DEFAULT_OUTPUT = os.path.join("firmware", "main", "af_lr_coefs.h")

HEADER_TEMPLATE = Template("""// Auto-generated by scripts/export_lr_coefs.py - DO NOT EDIT
// 7-parameter logistic regression for AF detection (RRI features)
// score = coef[0..5] * feat[0..5] + bias ; p_af = sigmoid(score)
// p_af >= k_af_lr_threshold -> anomaly (AF)
//
// Features:
//   feat[0] rri_std   RR interval std (ms)
//   feat[1] rmssd     sqrt(mean(diff(RRI)^2)) (ms)
//   feat[2] pnn50     fraction |diff(RRI)| > 50ms
//   feat[3] cv        RRI std / RRI mean
//   feat[4] hr_proxy  beats/sec proxy
//   feat[5] diff_std  std of first difference of waveform
//
// Source: model/af/af_model_lr.npz (val AUC 0.928, patient-isolated)

#pragma once

#include <stdint.h>

#define K_AF_LR_N_FEATURES 6
#define K_AF_LR_N_PARAMS   7

static const float k_af_lr_coef[K_AF_LR_N_FEATURES] = {
$coef_lines
};

static const float k_af_lr_bias = ${bias}f;

static const float k_af_lr_threshold = 0.5f;

static inline float af_lr_score(const float feat[K_AF_LR_N_FEATURES])
{
    float s = k_af_lr_bias;
    for (int i = 0; i < K_AF_LR_N_FEATURES; i++) {
        s += k_af_lr_coef[i] * feat[i];
    }
    return s;
}

static inline float af_lr_sigmoid(float z)
{
    return 1.0f / (1.0f + __builtin_expf(-z));
}
""")


def format_coefs(coef):
    """按每行 3 项排布，保留 7 位有效数字。"""
    lines = []
    row = []
    for v in coef:
        row.append(f"{v:.7g}f")
        if len(row) == 3:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Export LR weights to firmware C header")
    parser.add_argument("--weights", default=DEFAULT_WEIGHTS)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not os.path.isfile(args.weights):
        raise SystemExit(f"weights not found: {args.weights}")

    w = np.load(args.weights)
    coef = np.asarray(w["coef"], dtype=np.float64)
    bias = float(w["intercept"])

    if coef.size != 6:
        raise SystemExit(f"unexpected coef size {coef.size} (expect 6)")

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    content = HEADER_TEMPLATE.substitute(coef_lines=format_coefs(coef),
                                         bias=f"{bias:.7g}")

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"wrote {args.output}")
    print(f"  coef    = {np.round(coef, 5).tolist()}")
    print(f"  bias    = {bias:.5f}")
    print(f"  threshold = 0.5")


if __name__ == "__main__":
    main()
